# Generated by Django 4.2.4 on 2023-09-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0002_remove_employee_address_remove_employee_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='employee',
            name='lastname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(default=0, max_length=12),
        ),
    ]
