# Generated by Django 4.2.4 on 2023-09-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0004_form2_rename_employee_form1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(default='', max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField(default=0, max_length=12)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
